makes the console works in async
I had to rename getSpritePixel to getSpritePixelLoc, as adding studio.h
to sdl/main.c made a conflict.

src/system/sdl/main.c:348:11: error: conflicting types for
‘getSpritePixel’; have ‘u8(const tic_tile *, s32,  s32)’ {aka ‘unsigned
char(const tic_tile *, int,  int)’}
  348 | static u8 getSpritePixel(const tic_tile* tiles, s32 x, s32 y)
      |           ^~~~~~~~~~~~~~
In file included from src/system/sdl/main.c:24:
src/studio/studio.h:258:4: note: previous declaration of
‘getSpritePixel’ with type ‘u8(tic_tile *, s32,  s32)’ {aka ‘unsigned
char(tic_tile *, int,  int)’}
  258 | u8 getSpritePixel(tic_tile* tiles, s32 x, s32 y);
      |    ^~~~~~~~~~~~~~