Fix NSwitch and Android, due to conflicting fn map2ram()
Fix Nintendo Switch and Android build.

Error was:
/__w/TIC-80/TIC-80/src/system/sdl/main.c:419:13: error: conflicting
types for 'map2ram'; have 'void(tic_mem *)'
  419 | static void map2ram(tic_mem* tic)
      |             ^~~~~~~
In file included from /__w/TIC-80/TIC-80/src/system/sdl/main.c:24:
[ 98%] Building C object
CMakeFiles/tic80.dir/src/system/nswitch/runtime.o
/__w/TIC-80/TIC-80/src/studio/studio.h:302:6: note: previous declaration
of 'map2ram' with type 'void(tic_ram *, const tic_map *)'
  302 | void map2ram(tic_ram* ram, const tic_map* src);
      |      ^~~~~~~