Update vendor/zip from v0.1.19 to v0.3.6 (#2883)
* Updates verdor/zip from v0.1.19 to v0.3.5

no need for the -DCMAKE_POLICY_VERSION_MINIMUM=3.5 flag anymore.

* uses zip v0.2.6 instead of v.3.5

due to:
zip/src/miniz.h:8503:30: error: comparison is always false due to
limited range of data type [-Werror=type-limits]
8503 |     if (((mz_uint64)buf_size > 0xFFFFFFFF) || (uncomp_size >
0xFFFFFFFF)) {

* tries zip v0.3.5 again

but with the -Wno-type-limits flag

* Update vendor/zip to 0.3.6

* Add -Wno-stringop-truncation to zip compile options

* Refactor compiler option checks for zip to only apply -Wno-stringop-truncation for GCC

* Fix for  Baremetal GCC treating string truncation warnings as errors

* Fix support for bare-metal environment by defining lstat as stat

* Format comment

---------

Co-authored-by: imsys <911254+imsys@users.noreply.github.com>