uses zip v0.2.6 instead of v.3.5
due to:
zip/src/miniz.h:8503:30: error: comparison is always false due to
limited range of data type [-Werror=type-limits]
8503 |     if (((mz_uint64)buf_size > 0xFFFFFFFF) || (uncomp_size >
0xFFFFFFFF)) {